#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S3,     compass,        sensorI2CCustom)
#pragma config(Sensor, S4,     IR_sensor,      sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     flyWheel,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C2_1,    gripper,              tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    patriot,              tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int dir;
int irStrength1, irStrength2, irStrength3, irStrength4, irStrength5;
//int position;
int compassOffset;
int direction;
int counter = 0;
int delta;
float gain=1;

#include "hitechnic-irseeker-v2.h"
#include "JoystickDriver.c";
//#include "hitechnic-sensormux.h";
#include "hitechnic-compass.h";
//#include "lego-touch.h";
//#include "lego-ultrasound.h";

void executeGeneral();
int getMax();
int getAngle(int direction);
int getAngleCounterClockwise(int direction);
int rightMulti = 1;

void goStrait(float dist);
void goStraitBack(float dist);
void turnClockwise(int angle);
void turnCounterClockwise(int angle);
int getAngleDif(int angle);
void goTo(int stage);
task main()
{


/*while(true){
getMax();
}*/
waitForStart();
  goStrait(0.8);

  turnCounterClockwise(90);



	if(getMax()>50){
		turnClockwise(90);

		goTo(0);
		wait1Msec(1000);
    goStrait(0.7);

	  executeGeneral();
  }
else{

	counter=0;

  	 compassOffset=HTMCreadHeading(compass);
     while(counter <3){
  	  motor[leftMotor]=15;
			motor[rightMotor]=50;
		if(HTMCreadHeading(compass)-compassOffset>=28){
		counter++;
		}
		else{
			counter=0;
		}
  }
    	  motor[leftMotor]=0;
			motor[rightMotor]=0;
	if(getMax()>50){

		turnClockwise(110);
    goStrait(1);

	  executeGeneral();
  }
  else{
return;
  	counter=0;

  	 compassOffset=HTMCreadHeading(compass);
     while(counter<3){
  	  motor[leftMotor]=15;
			motor[rightMotor]=30;
					if(HTMCreadHeading(compass)-compassOffset>=28){
		counter++;
		}
		else{
			counter=0;
		}
  }
    	  motor[leftMotor]=0;
			motor[rightMotor]=0;
	turnClockwise(97);
    goStrait(0.5);

  	  executeGeneral();
  }
 }




}

void executeGeneral(){

	wait1Msec(1000);
     goStraitBack(0.5);
     turnClockwise(80);
     goStrait(1);
     turnCounterClockwise(90);
     motor[leftMotor]=100;
     motor[rightMotor]=100;
     wait1Msec(2000);

}
int getMax(){
		HTIRS2readAllACStrength(IR_sensor,irStrength1,irStrength2,irStrength3,irStrength4,irStrength5);
int currentMax=0;
if(irStrength1>currentMax){
   currentMax=irStrength1;
}
if(irStrength2>currentMax){
   currentMax=irStrength2;
}
if(irStrength3>currentMax){
   currentMax=irStrength3;
}
if(irStrength4>currentMax){
   currentMax=irStrength4;
}
if(irStrength5>currentMax){
   currentMax=irStrength5;
}
return currentMax;

}

int getAngle(int direction){
//	int toReturn=0;
  if(direction<-5){
  	return direction+360;
  }
  else if(direction<0){
  	return 0;
  }
  else{
  return direction;
}
}
int getAngleCounterClockwise(int direction){
//	int toReturn=0;
  if(direction>5){
  	return direction-360;
  }
  else if(direction>0){
  	return 0;
  }
  else{
  return direction;
}
}

void goStrait(float dist){
			    nMotorEncoder[leftMotor]=0;
    nMotorEncoder[rightMotor]=0;
    compassOffset=HTMCreadHeading(compass);


    while(nMotorEncoder[rightMotor]<dist*1120){

    	delta = getAngleDif(HTMCreadHeading(compass) - compassOffset);

     	motor[leftMotor] = 50+delta*gain;
			motor[rightMotor]= 50-delta*gain;
  }
  motor[leftMotor]=0;
  motor[rightMotor]=0;

}
void goStraitBack(float dist){
			    nMotorEncoder[leftMotor]=0;
    nMotorEncoder[rightMotor]=0;
    compassOffset=HTMCreadHeading(compass);


    while(nMotorEncoder[rightMotor]>-dist*1120){

    	delta = getAngleDif(HTMCreadHeading(compass) - compassOffset);

     	motor[leftMotor] = -50-delta*gain;
			motor[rightMotor]= -50+delta*gain;
  }
  motor[leftMotor]=0;
  motor[rightMotor]=0;

}
void turnClockwise(int angle){

    	 compassOffset=HTMCreadHeading(compass);
    	 counter=0;
     while(counter<3){
       direction=getAngle(HTMCreadHeading(compass)-compassOffset);
  	  motor[leftMotor]=-30;
			motor[rightMotor]=30*rightMulti;
			if(getAngle(HTMCreadHeading(compass)-compassOffset)>=angle){
		counter++;
		}
		else{
			counter=0;
		}
  }

    motor[leftMotor]=0;
    motor[rightMotor]=0;
     wait1Msec(1000);
}
void turnCounterClockwise(int angle){
	 counter=0;
  compassOffset=HTMCreadHeading(compass);
  while(counter <3 ){
  	  motor[leftMotor]=30;
			motor[rightMotor]=-30*rightMulti;
       direction=getAngleCounterClockwise(HTMCreadHeading(compass)-compassOffset);
			if(getAngleCounterClockwise(HTMCreadHeading(compass)-compassOffset)<=-angle){
		counter++;
		}
		else{
			counter=0;
		}
  }
  motor[leftMotor]=0;
  motor[rightMotor]=0;
   wait1Msec(1000);
}
int getAngleDif(int angle){
	if(angle>180){
	   return 360-angle;
  }
  else if(angle<-180){
     return -360-angle;
  }
  else{
     return angle;
  }
}
void goTo(int stage){
	int heights[] = {0,3,7,13};
	motor[lift]=0;

	if(nMotorEncoder[lift]< heights[stage]){
		while (nMotorEncoder[lift] < 1120*heights[stage] ) {
				motor[lift] =70;

			}
			motor[lift]=0;
					return;
	}
	else{
				while (nMotorEncoder[lift] > -1120*heights[stage] ) {
				motor[lift] = -10;

			}
			motor[lift]=0;
					return;
	motor[lift]=0;
		return;
}

}
