#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     msensor,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";
#include "hitechnic-sensormux.h";
#include "hitechnic-compass.h";
#include "lego-touch.h";
#include "lego-ultrasound.h";

int getAngleClockwise(int direction);

int getAngleCounterClockwise(int direction);

int direction;
int counter;
int compassOffset;
task main()
{
		    nMotorEncoder[leftMotor]=0;
    nMotorEncoder[rightMotor]=0;
    while(nMotorEncoder[rightMotor]>-0.1*1120){
    	motor[leftMotor]=-50;
			motor[rightMotor]=-50;
  }
      	motor[leftMotor]=0;
			motor[rightMotor]=0;

    	 compassOffset=HTMCreadHeading(msensor_S2_3);
    	 counter=0;
     while(counter<3){
       direction=getAngleClockwise(HTMCreadHeading(msensor_S2_3)-compassOffset);
  	  motor[leftMotor]=25;
			motor[rightMotor]=7;
			if(getAngleClockwise(HTMCreadHeading(msensor_S2_3)-compassOffset)>=45){
		counter++;
		}
		else{
			counter=0;
		}
  }
        	motor[leftMotor]=0;
			motor[rightMotor]=0;
  		    nMotorEncoder[leftMotor]=0;
    nMotorEncoder[rightMotor]=0;
    while(nMotorEncoder[rightMotor]<2*1120){
    	motor[leftMotor]=25;
			motor[rightMotor]=25;
  }
      	motor[leftMotor]=0;
			motor[rightMotor]=0;
  
      	 compassOffset=HTMCreadHeading(msensor_S2_3);
    	 counter=0;
     while(counter<3){
       direction=getAngleCounterClockwise(HTMCreadHeading(msensor_S2_3)-compassOffset);
  	  motor[leftMotor]=3;
			motor[rightMotor]=25;
			if(getAngleCounterClockwise(HTMCreadHeading(msensor_S2_3)-compassOffset)<=-45){
		counter++;
		}
		else{
			counter=0;
		}
  }
		motor[leftMotor]=0;
			motor[rightMotor]=0;
  		    nMotorEncoder[leftMotor]=0;
    nMotorEncoder[rightMotor]=0;
    while(nMotorEncoder[rightMotor]<6*1120){
    	motor[leftMotor]=25;
			motor[rightMotor]=20;
  }
      	motor[leftMotor]=0;
			motor[rightMotor]=0;
			

}

int getAngleClockwise(int direction){
	int toReturn=0;
  if(direction<-5){
  	return direction+360;
  }
  else if(direction<0){
  	return 0;
  }
  else{
  return direction;
}
}
int getAngleCounterClockwise(int direction){
	int toReturn=0;
  if(direction>5){
  	return direction-360;
  }
  else if(direction>0){
  	return 0;
  }
  else{
  return direction;
}
}
