#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     distance,       sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";
int dist;
bool goLeft=false;
task main()
{
	while(true)
	{
		dist=SensorValue[distance];
		goLeft = dist<20 || dist==255;
		if(goLeft){
			motor[leftMotor]=0;
			motor[rightMotor]=-50;
	}
	else{
			motor[leftMotor]=-50;
			motor[rightMotor]=0;
}

		//getJoystickSettings(joystick);
		//motor[leftMotor] = floor(joystick.joy1_y1/100)*-10;
		//motor[rightMotor] = floor(joystick.joy1_y2/100)*-10;
	}
}
