#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    gripperElbow,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    gripperWrist,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//#include "liftFinal.c"

int speedMod = 1;
int intakeForward=1;

void lowerGripper();
void raiseGripper();

task drive(){
	while(true){
		getJoystickSettings(joystick);
		if(joy1Btn(1)==1){
				speedMod = 6;
			}
			else if(joy1Btn(2)==1) {
				speedMod = 4;
			}
			else if(joy1Btn(3)==1) {
				speedMod = 1;
			}
		if(abs(joystick.joy1_y1)>10){
			motor[leftMotor] = joystick.joy1_y1/speedMod;
		}
		else{
			motor[leftMotor]=0;
		}
		if(abs(joystick.joy1_y2)>10){
			motor[rightMotor] = -joystick.joy1_y2/speedMod;
		}
		else{
			motor[rightMotor]=0;
		}
	}

}


task main()
{
	//	motor[leftMotor]=50;
	//	motor[rightMotor]=-50;
		//wait1Msec(10000);
//servo[gripperElbow]=0;
//servo[gripperWrist]=0;

waitForStart();
StartTask(drive);
//StartTask(lift);
//servo[ballShoot]=90;
	while(true){

  // motor[flywheelBig]=100;
  // /motor[flywheelSmall]=100;
   if(intakeForward==1){
      // servo[intake]=255;

 }
 else{
        //  servo[intake]=-255;
}
   if(joy2Btn(5)==1){
     lowerGripper();
 }
    if(joy2Btn(6)==1){
     raiseGripper();
 }
     if(joy2Btn(7)==1){
     intakeForward=1;
 }
     if(joy2Btn(8)==1){
     intakeForward=0;
 }
	}

}

void lowerGripper(){

servo[gripperElbow]=255;
servo[gripperWrist]=255;
}

void raiseGripper(){

servo[gripperElbow]=10;
servo[gripperWrist]=255;
}
