#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S3,     ,               sensorI2CCustom)
#pragma config(Sensor, S4,     ,               sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     flyWheel,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C2_1,    gripper,              tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    patriot,              tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


int speedMod = 1;
int intakeForward=1;
int openPatriot = 125;
int flySpeed = 0;
bool grip = true;
bool intak = true;
bool gripReady = false;
bool intakReady = false;
bool btn1 = false;
bool btn2 = false;
bool patriotism = false;

void goTo(int stage);
void lowerGripper();
void raiseGripper();
void controls();

task drive(){
	while(true ){
		if(patriotism){
		servo[patriot]=openPatriot;
		} else {
		servo[patriot]=75;
		}
		getJoystickSettings(joystick);
		if(joy1Btn(1)==1){
				speedMod = 6;
			}
			else if(joy1Btn(2)==1) {
				speedMod = 4;
			}
			else if(joy1Btn(3)==1) {
				speedMod = 1;
			}
		if(abs(joystick.joy1_y1)>10){
			motor[leftMotor] = -joystick.joy1_y1/speedMod;
		}
		else{
			motor[leftMotor]=0;
		}
		if(abs(joystick.joy1_y2)>10){
			motor[rightMotor] = -joystick.joy1_y2/speedMod;
		}
		else{
			motor[rightMotor]=0;
		}
		if (intak){
			intakeForward=1;
		} else{
			intakeForward=0;
		}
		if (grip){
			lowerGripper();
		} else{
			raiseGripper();
		}
	}

}

void controls(){
		while(true){


 if(flySpeed<50){
			flySpeed++;
			wait1Msec(500);
	}
	else{
nMotorPIDSpeedCtrl[flyWheel]=mtrSpeedReg;
}


	if(intakeForward==1){
//motor[intake]=10;
}
else{
//motor[intake]=-10;
}
//motor[flyWheel]=flySpeed;

   if(joy2Btn(5)==1){
     gripReady = true;
 }
   if(joy2Btn(5)==0){
    if(gripReady){
   		grip = !grip;
 			gripReady = false;
   	}
  }
    if(joy2Btn(6)==1){
     intakReady = true;
 }
 		if(joy2Btn(6)==0){
 			if(intakReady){
 				intak = !intak;
 				intakReady = false;
 			}
 		}
    if(joy2Btn(7)==1){
			btn1 = true;
 }
    if(joy2Btn(8)==1){
     	btn2 = true;
 }
 //HELLO GRANT
 //HELLO
 //HELLO
    if(joy2Btn(7)==0){
    	if(btn1){
   		openPatriot = openPatriot - 10;
 			btn1 = false;
 			patriotism = true;
   	}
 }
    if(joy2Btn(8)==0){
      if(btn2){
   		openPatriot = openPatriot + 10;
 			btn2 = false;
 			patriotism = true;

   	}
   	//DONE
   	//DONE
   	if(joy2Btn(1)==1){
   motor[lift]=40;
  }
  else if(joy2Btn(2)==1){
   motor[lift]=-40;
}
else{
motor[lift]=0;
}
 }
}
}

task main()
{

nMotorEncoder[lift] = 0;

waitForStart();
StartTask(drive);
controls();
}

void lowerGripper(){
servo[gripper] = 130;
}

void raiseGripper(){
servo[gripper] = 110;
}

void goTo(int stage){
	int heights[] = {0,3,7,13};
	motor[lift]=0;

	if(nMotorEncoder[lift]< heights[stage]){
		while (nMotorEncoder[lift] < 1120*heights[stage] ) {
				motor[lift] =50;

			}
			motor[lift]=0;
					return;
	}
	else{
				while (nMotorEncoder[lift] > -1120*heights[stage] ) {
				motor[lift] = -10;

			}
			motor[lift]=0;
					return;
	motor[lift]=0;
		return;
}

}
