#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          liftOne,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          liftTwo,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          liftThree,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    gripper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* #include "liftFinal.c"; */
#include "JoystickDriver.c";

int speedMod = 1;

task drive(){
	while(true){
		getJoystickSettings(joystick);
		if(joy1Btn(1)==1){
				speedMod = 8;
			}
			else if(joy1Btn(2)==1) {
				speedMod = 1;
			}
			else if(joy1Btn(3)==1) {
				speedMod = 0.5;
			}
		if(abs(joystick.joy1_y1)>10){
			motor[leftMotor] = joystick.joy1_y1/speedMod;
		}
		else{
			motor[leftMotor]=0;
		}
		if(abs(joystick.joy1_y2)>10){
			motor[rightMotor] = joystick.joy1_y2/speedMod;
		}
		else{
			motor[rightMotor]=0;
		}
	}

}


task main()
{

	StartTask(drive);
//*	StartTask(lift); */
	while(true){
		if(joy1Btn(6)==1){
			servo[gripper]=255;
		}
		if(joy1Btn(5)==1){
			servo[gripper]=0;
		}

	}

}
